import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { ApiItem, ApiService, Page } from '../../core/api.service';

@Component({selector:'app-cards-page',imports:[ReactiveFormsModule],template:`
<header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Crédito</p><h1 class="mt-1 text-3xl font-black">Cartões e faturas</h1><p class="mt-2 text-slate-500">Compras, parcelas e pagamentos sem duplicar despesas.</p></div><div class="flex gap-2"><button class="btn-secondary" (click)="showCardForm.set(true)">Novo cartão</button><button class="btn-primary" [disabled]="cards().length===0" (click)="showPurchaseForm.set(true)">Nova compra</button></div></header>
@if(message()){<p class="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800" role="status">{{message()}}</p>}@if(error()){<p class="mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700" role="alert">{{error()}}</p>}
<div class="mt-8 flex gap-2 overflow-x-auto">@for(item of tabs;track item.value){<button class="rounded-xl px-4 py-2 text-sm font-bold" [class.bg-slate-950]="tab()===item.value" [class.text-white]="tab()===item.value" [class.bg-white]="tab()!==item.value" (click)="tab.set(item.value)">{{item.label}}</button>}</div>
@if(tab()==='cards'){<section class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@for(card of cards();track card.id){<article class="card p-5"><div class="flex items-start justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">{{card['institution']||'Cartão'}}</p><h2 class="mt-1 text-xl font-black">{{card['name']}}</h2></div><span class="status-pill">{{card['active']?'Ativo':'Inativo'}}</span></div><div class="mt-6 grid grid-cols-2 gap-3"><div><p class="text-sm text-slate-500">Limite total</p><p class="text-xl font-black">{{money(card['credit_limit'])}}</p></div><div><p class="text-sm text-slate-500">Disponível</p><p class="text-xl font-black text-emerald-700">{{money(card['available_limit'])}}</p></div></div><p class="mt-2 text-xs text-slate-400">Em uso: {{money(card['used_limit'])}}</p><p class="mt-3 text-sm text-slate-500">Fecha dia {{card['closing_day']}} · vence dia {{card['due_day']}}</p><div class="mt-5 flex gap-2"><button class="btn-secondary !py-1.5 text-sm" (click)="editCard(card)">Editar</button><button class="rounded-lg px-3 py-1.5 text-sm font-bold text-red-600" (click)="removeCard(card)">Arquivar</button></div></article>}@empty{<p class="card p-10 text-center text-slate-500 md:col-span-2">Cadastre um cartão para lançar compras.</p>}</section>}
@if(tab()==='purchases'){<section class="card mt-5 divide-y divide-slate-100">@for(purchase of purchases();track purchase.id){<article class="p-5"><div class="flex justify-between gap-4"><div><h2 class="font-black">{{purchase['description']}}</h2><p class="mt-1 text-sm text-slate-500">{{purchase['purchased_at']}} · {{purchase['installment_count']}} parcela(s)</p></div><p class="font-black">{{money(purchase['total_amount'])}}</p></div><div class="mt-3 flex flex-wrap gap-2">@for(part of list(purchase,'installments');track part.id){<span class="status-pill">{{part['number']}}/{{purchase['installment_count']}} · {{money(part['amount'])}} · {{part['competence_date']}}</span>}</div></article>}@empty{<p class="p-10 text-center text-slate-500">Nenhuma compra registrada.</p>}</section>}
@if(tab()==='invoices'){<section class="card mt-5 divide-y divide-slate-100">@for(invoice of invoices();track invoice.id){<article class="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-black">{{nestedName(invoice,'credit_card')}}</h2><p class="mt-1 text-sm text-slate-500">Vencimento {{invoice['due_date']}} · <span class="font-bold">{{invoiceStatus(invoice['status'])}}</span></p><p class="mt-1 text-xs text-slate-400">{{list(invoice,'installments').length}} parcela(s) nesta fatura</p></div><div class="flex items-center gap-4"><p class="text-xl font-black">{{money(invoice['total'])}}</p>@if(invoice['status']!=='paid'){<button class="btn-primary !py-2" (click)="pay(invoice)">Pagar fatura</button>}</div></article>}@empty{<p class="p-10 text-center text-slate-500">Nenhuma fatura gerada.</p>}</section>}
@if(showCardForm()){<div class="modal-backdrop" role="dialog" aria-modal="true" aria-label="Formulário de cartão"><form class="card w-full max-w-xl p-6" [formGroup]="cardForm" (ngSubmit)="saveCard()"><div class="flex justify-between"><h2 class="text-xl font-black">{{editingCard()?'Editar':'Novo'}} cartão</h2><button type="button" aria-label="Fechar" (click)="closeCardForm()">✕</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label><span class="label">Nome</span><input class="field" formControlName="name"></label><label><span class="label">Instituição</span><input class="field" formControlName="institution"></label><label><span class="label">Conta para pagamento</span><select class="field" formControlName="payment_account_id"><option value="">Selecione</option>@for(account of accounts();track account.id){<option [value]="account.id">{{account['name']}}</option>}</select></label><label><span class="label">Limite</span><input class="field" type="number" step="0.01" formControlName="credit_limit"></label><label><span class="label">Dia de fechamento</span><input class="field" type="number" min="1" max="28" formControlName="closing_day"></label><label><span class="label">Dia de vencimento</span><input class="field" type="number" min="1" max="28" formControlName="due_day"></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" (click)="closeCardForm()">Cancelar</button><button class="btn-primary" [disabled]="cardForm.invalid||saving()">Salvar</button></div></form></div>}
@if(showPurchaseForm()){<div class="modal-backdrop" role="dialog" aria-modal="true" aria-label="Nova compra no cartão"><form class="card w-full max-w-xl p-6" [formGroup]="purchaseForm" (ngSubmit)="savePurchase()"><div class="flex justify-between"><h2 class="text-xl font-black">Nova compra</h2><button type="button" aria-label="Fechar" (click)="showPurchaseForm.set(false)">✕</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label><span class="label">Cartão</span><select class="field" formControlName="credit_card_id"><option value="">Selecione</option>@for(card of cards();track card.id){<option [value]="card.id">{{card['name']}}</option>}</select></label><label><span class="label">Categoria</span><select class="field" formControlName="category_id"><option value="">Sem categoria</option>@for(category of categories();track category.id){<option [value]="category.id">{{category['name']}}</option>}</select></label><label class="sm:col-span-2"><span class="label">Descrição</span><input class="field" formControlName="description"></label><label><span class="label">Valor total</span><input class="field" type="number" step="0.01" formControlName="total_amount"></label><label><span class="label">Parcelas</span><input class="field" type="number" min="1" max="120" formControlName="installment_count"></label><label><span class="label">Data da compra</span><input class="field" type="date" formControlName="purchased_at"></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" (click)="showPurchaseForm.set(false)">Cancelar</button><button class="btn-primary" [disabled]="purchaseForm.invalid||saving()">Gerar parcelas</button></div></form></div>}
`})
export class CardsPage{
  private readonly api=inject(ApiService);private readonly fb=inject(FormBuilder);readonly cards=signal<ApiItem[]>([]);readonly accounts=signal<ApiItem[]>([]);readonly categories=signal<ApiItem[]>([]);readonly purchases=signal<ApiItem[]>([]);readonly invoices=signal<ApiItem[]>([]);readonly tab=signal<'cards'|'purchases'|'invoices'>('cards');readonly showCardForm=signal(false);readonly showPurchaseForm=signal(false);readonly saving=signal(false);readonly message=signal('');readonly error=signal('');readonly editingCard=signal<ApiItem|null>(null);readonly tabs=[{label:'Cartões',value:'cards' as const},{label:'Compras e parcelas',value:'purchases' as const},{label:'Faturas',value:'invoices' as const}];
  readonly cardForm=this.fb.nonNullable.group({name:['',Validators.required],institution:[''],payment_account_id:['',Validators.required],credit_limit:['',Validators.required],closing_day:['',Validators.required],due_day:['',Validators.required],active:[true]});
  readonly purchaseForm=this.fb.nonNullable.group({credit_card_id:['',Validators.required],category_id:[''],description:['',Validators.required],total_amount:['',Validators.required],installment_count:['1',Validators.required],purchased_at:[new Date().toISOString().slice(0,10),Validators.required]});
  constructor(){this.load();}
  load():void{this.api.get<Page<ApiItem>>('cards',{per_page:100}).subscribe(r=>this.cards.set(r.data));this.api.get<Page<ApiItem>>('accounts',{per_page:100,sort:'name',direction:'asc'}).subscribe(r=>this.accounts.set(r.data));this.api.get<Page<ApiItem>>('categories',{per_page:100,type:'expense',sort:'name',direction:'asc'}).subscribe(r=>this.categories.set(r.data));this.api.get<Page<ApiItem>>('card-purchases',{per_page:100}).subscribe(r=>this.purchases.set(r.data));this.api.get<Page<ApiItem>>('invoices',{per_page:100}).subscribe(r=>this.invoices.set(r.data));}
  editCard(card:ApiItem):void{this.editingCard.set(card);this.cardForm.patchValue({name:String(card['name']),institution:String(card['institution']??''),payment_account_id:String(card['payment_account_id']),credit_limit:String(card['credit_limit']),closing_day:String(card['closing_day']),due_day:String(card['due_day']),active:Boolean(card['active'])});this.showCardForm.set(true);}
  closeCardForm():void{this.showCardForm.set(false);this.editingCard.set(null);this.cardForm.reset({name:'',institution:'',payment_account_id:'',credit_limit:'',closing_day:'',due_day:'',active:true});}
  saveCard():void{if(this.cardForm.invalid)return;this.saving.set(true);this.error.set('');const card=this.editingCard();const request=card?this.api.patch(`cards/${card.id}`,this.cardForm.getRawValue()):this.api.post('cards',this.cardForm.getRawValue());request.pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.message.set(card?'Cartão atualizado.':'Cartão criado.');this.closeCardForm();this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível salvar o cartão.')});}
  removeCard(card:ApiItem):void{if(confirm('Arquivar este cartão?'))this.api.delete(`cards/${card.id}`).subscribe({next:()=>{this.message.set('Cartão arquivado.');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível arquivar o cartão.')});}
  savePurchase():void{if(this.purchaseForm.invalid)return;this.saving.set(true);this.error.set('');const body={...this.purchaseForm.getRawValue(),category_id:this.purchaseForm.value.category_id||null};this.api.post('card-purchases',body).pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.showPurchaseForm.set(false);this.purchaseForm.reset({credit_card_id:'',category_id:'',description:'',total_amount:'',installment_count:'1',purchased_at:new Date().toISOString().slice(0,10)});this.message.set('Compra e parcelas registradas.');this.tab.set('purchases');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível registrar a compra.')});}
  pay(invoice:ApiItem):void{if(confirm(`Confirmar pagamento de ${this.money(invoice['total'])}?`))this.api.post(`invoices/${invoice.id}/pay`,{}).subscribe({next:()=>{this.message.set('Fatura paga e conta atualizada.');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível pagar a fatura.')});}
  list(item:ApiItem,key:string):ApiItem[]{return Array.isArray(item[key])?item[key] as ApiItem[]:[];}
  nestedName(item:ApiItem,key:string):string{return String((item[key] as ApiItem|undefined)?.['name']??'Cartão');}
  money(value:unknown):string{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}
  invoiceStatus(value:unknown):string{return {open:'Aberta',closed:'Fechada',paid:'Paga',overdue:'Vencida'}[String(value)]??String(value);}
}
