server {
    listen 80;
    server_name _;
    client_max_body_size 6m;

    location /api/ {
        root /var/www/html/public;
        try_files $uri /index.php?$query_string;
    }

    location ~ ^/index\.php(/|$) {
        root /var/www/html/public;
        fastcgi_pass backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    location / { proxy_pass http://frontend:80; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}
