import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { ApiItem, ApiService, Page } from '../../core/api.service';

@Component({selector:'app-goals-page',imports:[ReactiveFormsModule],template:`
<header class="flex items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Planejamento</p><h1 class="mt-1 text-3xl font-black">Metas financeiras</h1><p class="mt-2 text-slate-500">Acompanhe cada contribuição e o progresso dos seus planos.</p></div><button class="btn-primary" (click)="openGoal()">Nova meta</button></header>
@if(message()){<p class="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800" role="status">{{message()}}</p>}
<section class="mt-8 grid gap-5 lg:grid-cols-2">@for(goal of goals();track goal.id){<article class="card p-6"><div class="flex justify-between gap-4"><div><h2 class="text-xl font-black">{{goal['name']}}</h2><p class="mt-1 text-sm text-slate-500">{{goal['description']}}</p></div><span class="status-pill">{{status(goal['status'])}}</span></div><div class="mt-6 flex justify-between text-sm font-semibold"><span>{{money(goal['current_amount'])}}</span><span>{{money(goal['target_amount'])}}</span></div><div class="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-500" [style.width.%]="percent(goal)"></div></div><p class="mt-2 text-sm text-slate-500">{{percent(goal)}}% alcançado · faltam {{remaining(goal)}}</p>@if(goal['target_date']){<p class="mt-1 text-xs text-slate-400">Prazo: {{goal['target_date']}}</p>}<div class="mt-5 flex flex-wrap gap-2"><button class="btn-primary !py-1.5 text-sm" (click)="openContribution(goal)">Contribuir</button><button class="btn-secondary !py-1.5 text-sm" (click)="openGoal(goal)">Editar</button><button class="rounded-lg px-3 py-1.5 text-sm font-bold text-red-600" (click)="remove(goal)">Excluir</button></div>@if(list(goal,'contributions').length){<details class="mt-5"><summary class="cursor-pointer text-sm font-bold text-slate-600">Histórico de contribuições</summary><div class="mt-2 divide-y divide-slate-100">@for(item of list(goal,'contributions');track item.id){<div class="flex justify-between py-2 text-sm"><span>{{item['contributed_at']}} {{item['notes']}}</span><b>{{money(item['amount'])}}</b></div>}</div></details>}</article>}@empty{<p class="card p-12 text-center text-slate-500 lg:col-span-2">Crie sua primeira meta financeira.</p>}</section>
@if(showGoalForm()){<div class="modal-backdrop" role="dialog" aria-modal="true" aria-label="Formulário de meta"><form class="card w-full max-w-xl p-6" [formGroup]="goalForm" (ngSubmit)="saveGoal()"><div class="flex justify-between"><h2 class="text-xl font-black">{{editing()?'Editar':'Nova'}} meta</h2><button type="button" aria-label="Fechar" (click)="showGoalForm.set(false)">✕</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Nome</span><input class="field" formControlName="name"></label><label class="sm:col-span-2"><span class="label">Descrição</span><textarea class="field" formControlName="description"></textarea></label><label><span class="label">Valor alvo</span><input class="field" type="number" step="0.01" formControlName="target_amount"></label><label><span class="label">Valor atual</span><input class="field" type="number" step="0.01" formControlName="current_amount"></label><label><span class="label">Data alvo</span><input class="field" type="date" formControlName="target_date"></label><label><span class="label">Status</span><select class="field" formControlName="status"><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option></select></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" (click)="showGoalForm.set(false)">Cancelar</button><button class="btn-primary" [disabled]="goalForm.invalid||saving()">Salvar</button></div></form></div>}
@if(contributing()){<div class="modal-backdrop" role="dialog" aria-modal="true" aria-label="Contribuição para meta"><form class="card w-full max-w-md p-6" [formGroup]="contributionForm" (ngSubmit)="saveContribution()"><div class="flex justify-between"><h2 class="text-xl font-black">Contribuir para {{contributing()?.['name']}}</h2><button type="button" aria-label="Fechar" (click)="contributing.set(null)">✕</button></div><div class="mt-5 space-y-4"><label><span class="label">Valor</span><input class="field" type="number" step="0.01" formControlName="amount"></label><label><span class="label">Data</span><input class="field" type="date" formControlName="contributed_at"></label><label><span class="label">Observação</span><textarea class="field" formControlName="notes"></textarea></label></div><button class="btn-primary mt-6 w-full" [disabled]="contributionForm.invalid||saving()">Registrar contribuição</button></form></div>}
`})
export class GoalsPage{
  private readonly api=inject(ApiService);private readonly fb=inject(FormBuilder);readonly goals=signal<ApiItem[]>([]);readonly message=signal('');readonly showGoalForm=signal(false);readonly editing=signal<ApiItem|null>(null);readonly contributing=signal<ApiItem|null>(null);readonly saving=signal(false);
  readonly goalForm=this.fb.nonNullable.group({name:['',Validators.required],description:[''],target_amount:['',Validators.required],current_amount:['0.00'],target_date:[''],status:['active',Validators.required]});readonly contributionForm=this.fb.nonNullable.group({amount:['',Validators.required],contributed_at:[new Date().toISOString().slice(0,10),Validators.required],notes:['']});
  constructor(){this.load();}load():void{this.api.get<Page<ApiItem>>('goals',{per_page:100,sort:'target_date',direction:'asc'}).subscribe(r=>this.goals.set(r.data));}
  openGoal(goal?:ApiItem):void{this.editing.set(goal??null);this.goalForm.reset({name:String(goal?.['name']??''),description:String(goal?.['description']??''),target_amount:String(goal?.['target_amount']??''),current_amount:String(goal?.['current_amount']??'0.00'),target_date:String(goal?.['target_date']??'').slice(0,10),status:String(goal?.['status']??'active')});this.showGoalForm.set(true);}
  saveGoal():void{if(this.goalForm.invalid)return;this.saving.set(true);const goal=this.editing();const body={...this.goalForm.getRawValue(),target_date:this.goalForm.value.target_date||null};const request=goal?this.api.patch(`goals/${goal.id}`,body):this.api.post('goals',body);request.pipe(finalize(()=>this.saving.set(false))).subscribe(()=>{this.showGoalForm.set(false);this.message.set(goal?'Meta atualizada.':'Meta criada.');this.load();});}
  openContribution(goal:ApiItem):void{this.contributing.set(goal);this.contributionForm.reset({amount:'',contributed_at:new Date().toISOString().slice(0,10),notes:''});}
  saveContribution():void{const goal=this.contributing();if(!goal||this.contributionForm.invalid)return;this.saving.set(true);this.api.post(`goals/${goal.id}/contributions`,this.contributionForm.getRawValue()).pipe(finalize(()=>this.saving.set(false))).subscribe(()=>{this.contributing.set(null);this.message.set('Contribuição registrada.');this.load();});}
  remove(goal:ApiItem):void{if(confirm('Excluir esta meta?'))this.api.delete(`goals/${goal.id}`).subscribe(()=>this.load());}
  percent(goal:ApiItem):number{return Math.min(100,Math.round(Number(goal['current_amount'])/Number(goal['target_amount'])*100)||0);}remaining(goal:ApiItem):string{return this.money(Math.max(0,Number(goal['target_amount'])-Number(goal['current_amount'])));}money(value:unknown):string{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}status(value:unknown):string{return {active:'Ativa',paused:'Pausada',completed:'Concluída'}[String(value)]??String(value);}list(item:ApiItem,key:string):ApiItem[]{return Array.isArray(item[key])?item[key] as ApiItem[]:[];}
}
