import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiItem, ApiService } from '../../core/api.service';
import { AuthService, User } from '../../core/auth.service';

@Component({selector:'app-settings',imports:[ReactiveFormsModule],template:`
<header><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Preferências</p><h1 class="mt-1 text-3xl font-black">Configurações</h1><p class="mt-2 text-slate-500">Perfil, localização, senha e dispositivos conectados.</p></header>
@if(message()){<p class="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800" role="status">{{message()}}</p>}
<div class="mt-8 grid gap-6 lg:grid-cols-2"><form class="card p-6" [formGroup]="profile" (ngSubmit)="saveProfile()"><h2 class="text-lg font-black">Perfil</h2><div class="mt-5 space-y-4"><label><span class="label">Nome</span><input class="field" formControlName="name"></label><label><span class="label">E-mail</span><input class="field" type="email" formControlName="email"></label><label><span class="label">Moeda</span><select class="field" formControlName="currency"><option value="BRL">Real brasileiro (BRL)</option></select></label><label><span class="label">Locale</span><select class="field" formControlName="locale"><option value="pt-BR">Português do Brasil</option></select></label><label><span class="label">Fuso horário</span><select class="field" formControlName="timezone"><option value="America/Sao_Paulo">América/São Paulo</option></select></label><button class="btn-primary" [disabled]="profile.invalid">Salvar preferências</button></div></form><form class="card p-6" [formGroup]="password" (ngSubmit)="changePassword()"><h2 class="text-lg font-black">Segurança</h2><div class="mt-5 space-y-4"><label><span class="label">Senha atual</span><input class="field" type="password" autocomplete="current-password" formControlName="current_password"></label><label><span class="label">Nova senha</span><input class="field" type="password" autocomplete="new-password" formControlName="password"></label><label><span class="label">Confirme a nova senha</span><input class="field" type="password" autocomplete="new-password" formControlName="password_confirmation"></label><button class="btn-primary" [disabled]="password.invalid">Alterar senha</button></div></form></div>
<section class="card mt-6 overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Sessões ativas</h2><p class="mt-1 text-sm text-slate-500">Revogue acessos de dispositivos que você não reconhece.</p></div>@for(session of sessions();track session.id){<div class="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{session['device_name']||'Dispositivo não identificado'}}</p><p class="mt-1 text-xs text-slate-400">IP {{session['ip_address']||'não informado'}} · criada em {{session['created_at']}}</p></div><button class="rounded-lg px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50" (click)="revoke(session)">Revogar</button></div>}@empty{<p class="p-8 text-center text-slate-500">Nenhuma sessão adicional ativa.</p>}</section>
`})
export class Settings{
  private readonly fb=inject(FormBuilder);private readonly api=inject(ApiService);private readonly auth=inject(AuthService);readonly message=signal('');readonly sessions=signal<ApiItem[]>([]);readonly profile=this.fb.nonNullable.group({name:[this.auth.user()?.name??'',Validators.required],email:[this.auth.user()?.email??'',[Validators.required,Validators.email]],currency:[this.auth.user()?.currency??'BRL'],locale:[this.auth.user()?.locale??'pt-BR'],timezone:[this.auth.user()?.timezone??'America/Sao_Paulo']});readonly password=this.fb.nonNullable.group({current_password:['',Validators.required],password:['',[Validators.required,Validators.minLength(10)]],password_confirmation:['',Validators.required]});
  constructor(){this.loadSessions();}saveProfile():void{this.api.patch<{data:User}>('auth/profile',this.profile.getRawValue()).subscribe(response=>{this.auth.updateUser(response.data);this.message.set('Preferências atualizadas.');});}changePassword():void{this.api.put('auth/password',this.password.getRawValue()).subscribe(()=>{this.message.set('Senha alterada e outras sessões revogadas.');this.password.reset();this.loadSessions();});}revoke(session:ApiItem):void{if(confirm('Revogar esta sessão?'))this.api.delete(`auth/sessions/${session.id}`).subscribe(()=>{this.message.set('Sessão revogada.');this.loadSessions();});}private loadSessions():void{this.api.get<{data:ApiItem[]}>('auth/sessions').subscribe(response=>this.sessions.set(response.data));}
}
