import { Component, OnInit, inject, input, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { ApiItem, ApiService, Page } from '../../core/api.service';
import { FieldDefinition, FieldOption, schemas } from './resource.schemas';

type FieldValue = string | string[];

@Component({selector:'app-resource-page',imports:[ReactiveFormsModule],template:`
<header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Organização financeira</p><h1 class="mt-1 text-3xl font-black">{{title()}}</h1><p class="mt-2 text-slate-500">{{description()}}</p></div><button class="btn-primary" (click)="openForm()">+ Novo registro</button></header>
@if(error()&&!showForm()){<p class="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{{error()}}</p>}
@if(success()){<p class="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800" role="status">{{success()}}</p>}
<section class="card mt-8 overflow-hidden"><div class="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-5"><label class="md:col-span-2"><span class="sr-only">Buscar</span><input class="field" placeholder="Buscar por nome ou descrição" [value]="search()" (input)="search.set($any($event.target).value)" (keyup.enter)="page.set(1);load()"></label>
@if(endpoint()==='transactions'){<label><span class="sr-only">Tipo</span><select class="field" [value]="filterType()" (change)="filterType.set($any($event.target).value);page.set(1);load()"><option value="">Todos os tipos</option><option value="income">Receitas</option><option value="expense">Despesas</option></select></label><label><span class="sr-only">Status</span><select class="field" [value]="filterStatus()" (change)="filterStatus.set($any($event.target).value);page.set(1);load()"><option value="">Todos os status</option><option value="planned">Previsto</option><option value="pending">Pendente</option><option value="paid">Pago</option><option value="received">Recebido</option><option value="overdue">Vencido</option><option value="cancelled">Cancelado</option></select></label>}
<label><span class="sr-only">Ordenar</span><select class="field" [value]="sort()" (change)="sort.set($any($event.target).value);load()"><option value="created_at">Mais recentes</option>@if(endpoint()==='transactions'||endpoint()==='transfers'){<option value="description">Descrição</option>}@else if(endpoint()==='budgets'){<option value="month">Mês</option>}@else{<option value="name">Nome</option>}@if(endpoint()==='transactions'){<option value="transaction_date">Data</option><option value="due_date">Vencimento</option>}</select></label><button class="btn-secondary" (click)="page.set(1);load()">Aplicar filtros</button></div>
@if(loading()){<div class="p-10 text-center text-slate-500">Carregando…</div>}@else if(items().length===0){<div class="p-12 text-center"><div class="text-4xl">◇</div><h2 class="mt-3 font-black">Nada por aqui ainda</h2><p class="mt-1 text-sm text-slate-500">Crie o primeiro registro para começar.</p></div>}@else{<div class="divide-y divide-slate-100">@for(item of items();track item.id){<article class="px-5 py-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{primary(item)}}</p><p class="mt-1 text-sm text-slate-500">{{secondary(item)}}</p></div><div class="flex flex-wrap items-center gap-2"><p class="mr-2 text-lg font-black text-slate-800">{{amount(item)}}</p>@if(endpoint()!=='transfers'){<button class="btn-secondary !px-3 !py-1.5 text-sm" (click)="openForm(item)">Editar</button>}@if(allowDelete()){<button class="rounded-lg px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50" (click)="remove(item)">Excluir</button>}</div></div>
@if(endpoint()==='transactions'){<div class="mt-3 flex flex-wrap items-center gap-2"><label class="cursor-pointer rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">Anexar comprovante<input class="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" (change)="uploadAttachment(item,$event)"></label>@for(file of attachments(item);track file.id){<span class="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-2 py-1"><button class="text-xs font-semibold text-emerald-700 underline" (click)="downloadAttachment(file)">{{file['original_name']}}</button><button class="px-1 text-xs font-black text-red-600" [attr.aria-label]="'Excluir '+file['original_name']" (click)="removeAttachment(file)">×</button></span>}</div>}
</article>}</div><footer class="flex items-center justify-between border-t border-slate-100 p-4 text-sm text-slate-500"><span>{{total()}} registro(s)</span><div class="flex gap-2"><button class="btn-secondary !px-3 !py-1.5" [disabled]="page()<=1" (click)="page.set(page()-1);load()">Anterior</button><span class="px-2 py-2">{{page()}} / {{lastPage()}}</span><button class="btn-secondary !px-3 !py-1.5" [disabled]="page()>=lastPage()" (click)="page.set(page()+1);load()">Próxima</button></div></footer>}
</section>
@if(showForm()){<div class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" [attr.aria-label]="editing()?'Editar registro':'Novo registro'" tabindex="-1" (click)="closeBackdrop($event)" (keydown.escape)="showForm.set(false)"><section class="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-black">{{editing()?'Editar':'Novo'}} registro</h2><button (click)="showForm.set(false)" aria-label="Fechar">✕</button></div><form class="mt-6 grid gap-4 sm:grid-cols-2" [formGroup]="form" (ngSubmit)="save()">@for(field of fields;track field.key){<label [for]="field.key" [class.sm:col-span-2]="field.type==='textarea'||field.type==='multiselect'"><span class="label">{{field.label}}</span>@if(field.type==='select'){<select class="field" [id]="field.key" [formControlName]="field.key"><option value="">Selecione</option>@for(option of optionsFor(field);track option.value){<option [value]="option.value">{{option.label}}</option>}</select>}@else if(field.type==='multiselect'){<select class="field min-h-28" multiple [id]="field.key" [formControlName]="field.key">@for(option of optionsFor(field);track option.value){<option [value]="option.value">{{option.label}}</option>}</select><span class="mt-1 block text-xs text-slate-400">Use Ctrl/Cmd para selecionar mais de uma opção.</span>}@else if(field.type==='textarea'){<textarea class="field" [id]="field.key" rows="3" [formControlName]="field.key"></textarea>}@else{<input class="field" [id]="field.key" [type]="field.type??'text'" [step]="field.type==='number'?'0.01':null" [placeholder]="field.placeholder??''" [formControlName]="field.key">}</label>}@if(error()){<p class="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{{error()}}</p>}<div class="flex justify-end gap-3 sm:col-span-2"><button type="button" class="btn-secondary" (click)="showForm.set(false)">Cancelar</button><button class="btn-primary" [disabled]="form.invalid||saving()">{{saving()?'Salvando…':'Salvar'}}</button></div></form></section></div>}
`})
export class ResourcePage implements OnInit {
  private readonly api=inject(ApiService);
  readonly endpoint=input.required<string>();readonly title=input.required<string>();readonly description=input('Cadastre, consulte e mantenha seus dados organizados.');readonly presetType=input('');readonly allowDelete=input(true);
  readonly items=signal<ApiItem[]>([]);readonly loading=signal(true);readonly showForm=signal(false);readonly saving=signal(false);readonly error=signal('');readonly success=signal('');readonly search=signal('');readonly filterType=signal('');readonly filterStatus=signal('');readonly sort=signal('created_at');readonly page=signal(1);readonly lastPage=signal(1);readonly total=signal(0);readonly editing=signal<ApiItem|null>(null);readonly lookupOptions=signal<Record<string,FieldOption[]>>({});
  form=new FormGroup<Record<string,FormControl<FieldValue>>>({});fields:FieldDefinition[]=[];
  ngOnInit():void{this.fields=(schemas[this.endpoint()]??[]).filter(field=>!(field.key==='type'&&this.presetType()));const controls:Record<string,FormControl<FieldValue>>={};for(const field of this.fields)controls[field.key]=new FormControl<FieldValue>(field.type==='multiselect'?[]:'',{nonNullable:true,validators:field.required?[Validators.required]:[]});if(this.presetType())controls['type']=new FormControl<FieldValue>(this.presetType(),{nonNullable:true});this.form=new FormGroup(controls);this.filterType.set(this.presetType());this.loadLookups();this.load();}
  load():void{this.loading.set(true);this.error.set('');this.api.get<Page<ApiItem>>(this.endpoint(),{page:this.page(),search:this.search(),sort:this.sort(),direction:'desc',...(this.filterType()?{type:this.filterType()}:{}),...(this.filterStatus()?{status:this.filterStatus()}:{})}).subscribe({next:r=>{this.items.set(r.data);this.lastPage.set(r.last_page);this.total.set(r.total);this.loading.set(false);},error:()=>{this.loading.set(false);this.error.set('Não foi possível carregar os registros. Tente novamente.');}});}
  openForm(item?:ApiItem):void{this.editing.set(item??null);this.form.reset();if(item){for(const field of this.fields){let value=item[field.key];if(field.key==='tag_ids')value=this.attachmentsLike(item,'tags').map(tag=>String(tag.id));if(field.type==='date'&&value)value=String(value).slice(0,10);if(field.type==='select'&&typeof value==='boolean')value=value?'1':'0';this.form.controls[field.key]?.setValue(Array.isArray(value)?value.map(String):String(value??''));}}else{if(this.presetType())this.form.controls['type'].setValue(this.presetType());const today=new Date().toISOString().slice(0,10);for(const key of ['transaction_date','competence_date','transferred_at','month'])this.form.controls[key]?.setValue(today);this.form.controls['status']?.setValue(this.presetType()==='income'?'received':'paid');this.form.controls['active']?.setValue('1');this.form.controls['is_fixed']?.setValue('0');}this.error.set('');this.showForm.set(true);}
  save():void{if(this.form.invalid)return;this.saving.set(true);this.error.set('');const body:Record<string,unknown>={...this.form.getRawValue()};for(const key of ['active','is_fixed'])if(key in body)body[key]=body[key]==='1';for(const [key,value] of Object.entries(body))if(value==='')body[key]=null;const item=this.editing();const request=item?this.api.patch(`${this.endpoint()}/${item.id}`,body):this.api.post(this.endpoint(),body);request.pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.showForm.set(false);this.success.set(item?'Registro atualizado.':'Registro criado.');this.load();},error:e=>this.error.set(e.error?.message??'Verifique os campos informados.')});}
  remove(item:ApiItem):void{if(!confirm('Deseja realmente remover este registro?'))return;this.api.delete(`${this.endpoint()}/${item.id}`).subscribe({next:()=>{this.success.set('Registro removido.');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível remover o registro.')});}
  uploadAttachment(item:ApiItem,event:Event):void{const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;const data=new FormData();data.append('file',file);this.api.post(`transactions/${item.id}/attachments`,data).subscribe({next:()=>{this.success.set('Comprovante anexado.');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível enviar o anexo.')});input.value='';}
  downloadAttachment(file:ApiItem):void{this.api.download(`attachments/${file.id}/download`).subscribe(blob=>{const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=String(file['original_name']??'comprovante');link.click();URL.revokeObjectURL(url);});}
  removeAttachment(file:ApiItem):void{if(!confirm('Excluir este comprovante?'))return;this.api.delete(`attachments/${file.id}`).subscribe({next:()=>{this.success.set('Comprovante removido.');this.load();},error:e=>this.error.set(e.error?.message??'Não foi possível remover o anexo.')});}
  optionsFor(field:FieldDefinition):FieldOption[]{return field.options??this.lookupOptions()[field.key]??[];}
  attachments(item:ApiItem):ApiItem[]{return this.attachmentsLike(item,'attachments');}
  closeBackdrop(event:MouseEvent):void{if(event.target===event.currentTarget)this.showForm.set(false);}
  primary(item:ApiItem):string{return String(item['name']??item['description']??`Registro #${item.id}`);}
  secondary(item:ApiItem):string{const account=(item['account'] as ApiItem|undefined)?.['name'];const category=(item['category'] as ApiItem|undefined)?.['name'];const budget=item['realized_amount']!==undefined?`Realizado ${this.money(item['realized_amount'])} · restante ${this.money(item['remaining_amount'])} · ${item['percentage']}%`:null;return [account,category,item['type'],item['status'],item['transaction_date']??item['transferred_at']??item['month'],budget].filter(Boolean).join(' · ');}
  amount(item:ApiItem):string{const value=item['amount']??item['current_balance']??item['planned_amount']??item['target_amount']??item['credit_limit'];return value===undefined?'':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}
  money(value:unknown):string{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}
  private loadLookups():void{for(const field of this.fields.filter(item=>item.source)){const params:Record<string,string|number>={per_page:100,sort:'name',direction:'asc'};if(field.sourceType)params['type']=field.sourceType;this.api.get<Page<ApiItem>>(field.source!,params).subscribe(response=>this.lookupOptions.update(options=>({...options,[field.key]:response.data.map(item=>({label:String(item['name']),value:String(item.id)}))})));}}
  private attachmentsLike(item:ApiItem,key:string):ApiItem[]{const value=item[key];return Array.isArray(value)?value as ApiItem[]:[];}
}
