export interface FieldOption { label:string;value:string }
export interface FieldDefinition { key:string;label:string;type?:'text'|'number'|'date'|'select'|'multiselect'|'textarea';required?:boolean;options?:FieldOption[];source?:'accounts'|'categories'|'tags';sourceType?:'income'|'expense';placeholder?:string }

const accountTypes=[{label:'Conta corrente',value:'checking'},{label:'Poupança',value:'savings'},{label:'Dinheiro',value:'cash'},{label:'Conta digital',value:'digital'},{label:'Investimento',value:'investment'},{label:'Outra',value:'other'}];
const transactionStatus=[{label:'Previsto',value:'planned'},{label:'Pendente',value:'pending'},{label:'Pago',value:'paid'},{label:'Recebido',value:'received'},{label:'Vencido',value:'overdue'},{label:'Cancelado',value:'cancelled'}];
const yesNo=[{label:'Sim',value:'1'},{label:'Não',value:'0'}];

export const schemas:Record<string,FieldDefinition[]>={
  accounts:[{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',type:'select',options:accountTypes,required:true},{key:'institution',label:'Instituição'},{key:'initial_balance',label:'Saldo inicial',type:'number',required:true},{key:'active',label:'Conta ativa',type:'select',options:yesNo},{key:'notes',label:'Observações',type:'textarea'}],
  transactions:[{key:'description',label:'Descrição',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'account_id',label:'Conta',type:'select',source:'accounts',required:true},{key:'category_id',label:'Categoria',type:'select',source:'categories'},{key:'tag_ids',label:'Tags',type:'multiselect',source:'tags'},{key:'type',label:'Tipo',type:'select',options:[{label:'Receita',value:'income'},{label:'Despesa',value:'expense'}],required:true},{key:'transaction_date',label:'Data da transação',type:'date',required:true},{key:'competence_date',label:'Competência',type:'date',required:true},{key:'due_date',label:'Vencimento',type:'date'},{key:'settled_at',label:'Pagamento/recebimento',type:'date'},{key:'status',label:'Status',type:'select',options:transactionStatus,required:true},{key:'is_fixed',label:'Lançamento fixo',type:'select',options:yesNo},{key:'notes',label:'Observações',type:'textarea'}],
  transfers:[{key:'from_account_id',label:'Conta de origem',type:'select',source:'accounts',required:true},{key:'to_account_id',label:'Conta de destino',type:'select',source:'accounts',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'transferred_at',label:'Data',type:'date',required:true},{key:'description',label:'Descrição'}],
  budgets:[{key:'category_id',label:'Categoria de despesa',type:'select',source:'categories',sourceType:'expense',required:true},{key:'month',label:'Mês',type:'date',required:true},{key:'planned_amount',label:'Valor planejado',type:'number',required:true}],
  categories:[{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',type:'select',options:[{label:'Receita',value:'income'},{label:'Despesa',value:'expense'}],required:true},{key:'parent_id',label:'Categoria principal',type:'select',source:'categories'},{key:'color',label:'Cor hexadecimal',placeholder:'#64748b'}],
  tags:[{key:'name',label:'Nome',required:true},{key:'color',label:'Cor hexadecimal',placeholder:'#0f766e'}],
};
