import { Component, OnInit, inject, input, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiItem, ApiService, Page } from '../../core/api.service';
import { FieldDefinition, schemas } from './resource.schemas';

@Component({selector:'app-resource-page',imports:[ReactiveFormsModule],template:`
<header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Organização financeira</p><h1 class="mt-1 text-3xl font-black">{{title()}}</h1><p class="mt-2 text-slate-500">{{description()}}</p></div><button class="btn-primary" (click)="openForm()">+ Novo registro</button></header>
<section class="card mt-8 overflow-hidden"><div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><label class="sr-only" for="resource-search">Buscar</label><input id="resource-search" class="field max-w-md" placeholder="Buscar por nome ou descrição" [value]="search()" (input)="search.set($any($event.target).value)" (keyup.enter)="load()"><button class="btn-secondary" (click)="load()">Buscar</button></div>
@if(loading()){<div class="p-10 text-center text-slate-500">Carregando…</div>}@else if(items().length===0){<div class="p-12 text-center"><div class="text-4xl">◇</div><h2 class="mt-3 font-black">Nada por aqui ainda</h2><p class="mt-1 text-sm text-slate-500">Crie o primeiro registro para começar.</p></div>}@else{<div class="divide-y divide-slate-100">@for(item of items();track item.id){<article class="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{primary(item)}}</p><p class="mt-1 text-sm text-slate-500">{{secondary(item)}}</p></div><div class="flex items-center gap-3"><p class="text-right text-lg font-black text-slate-800">{{amount(item)}}</p>@if(allowDelete()){<button class="rounded-lg px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50" (click)="remove(item)">Excluir</button>}</div></article>}</div><footer class="flex items-center justify-between border-t border-slate-100 p-4 text-sm text-slate-500"><span>{{total()}} registro(s)</span><div class="flex gap-2"><button class="btn-secondary !px-3 !py-1.5" [disabled]="page()<=1" (click)="page.set(page()-1);load()">Anterior</button><span class="px-2 py-2">{{page()}} / {{lastPage()}}</span><button class="btn-secondary !px-3 !py-1.5" [disabled]="page()>=lastPage()" (click)="page.set(page()+1);load()">Próxima</button></div></footer>}
</section>
@if(showForm()){<div class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label="Novo registro" tabindex="-1" (click)="closeBackdrop($event)" (keydown.escape)="showForm.set(false)"><section class="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Novo registro</h2><button (click)="showForm.set(false)" aria-label="Fechar">✕</button></div><form class="mt-6 grid gap-4 sm:grid-cols-2" [formGroup]="form" (ngSubmit)="save()">@for(field of fields;track field.key){<label [for]="field.key" [class.sm:col-span-2]="field.type==='textarea'"><span class="label">{{field.label}}</span>@if(field.type==='select'){<select class="field" [id]="field.key" [formControlName]="field.key"><option value="">Selecione</option>@for(option of field.options;track option.value){<option [value]="option.value">{{option.label}}</option>}</select>}@else if(field.type==='textarea'){<textarea class="field" [id]="field.key" rows="3" [formControlName]="field.key"></textarea>}@else{<input class="field" [id]="field.key" [type]="field.type??'text'" [step]="field.type==='number'?'0.01':null" [formControlName]="field.key">}</label>}@if(error()){<p class="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{{error()}}</p>}<div class="flex justify-end gap-3 sm:col-span-2"><button type="button" class="btn-secondary" (click)="showForm.set(false)">Cancelar</button><button class="btn-primary" [disabled]="form.invalid||saving()">{{saving()?'Salvando…':'Salvar'}}</button></div></form></section></div>}
`})
export class ResourcePage implements OnInit {
  private readonly api=inject(ApiService);
  readonly endpoint=input.required<string>();readonly title=input.required<string>();readonly description=input('Cadastre, consulte e mantenha seus dados organizados.');readonly presetType=input('');readonly allowDelete=input(true);
  readonly items=signal<ApiItem[]>([]);readonly loading=signal(true);readonly showForm=signal(false);readonly saving=signal(false);readonly error=signal('');readonly search=signal('');readonly page=signal(1);readonly lastPage=signal(1);readonly total=signal(0);form=new FormGroup<Record<string,FormControl<string>>>({});fields:FieldDefinition[]=[];
  ngOnInit():void{this.fields=(schemas[this.endpoint()]??[]).filter(field=>!(field.key==='type'&&this.presetType()));const controls:Record<string,FormControl<string>>={};for(const field of this.fields)controls[field.key]=new FormControl('',{nonNullable:true,validators:field.required?[Validators.required]:[]});if(this.presetType())controls['type']=new FormControl(this.presetType(),{nonNullable:true});this.form=new FormGroup(controls);this.load();}
  load():void{this.loading.set(true);this.api.get<Page<ApiItem>>(this.endpoint(),{page:this.page(),search:this.search(),...(this.presetType()?{type:this.presetType()}:{})}).subscribe({next:r=>{this.items.set(r.data);this.lastPage.set(r.last_page);this.total.set(r.total);this.loading.set(false);},error:()=>this.loading.set(false)});}
  openForm():void{this.form.reset();if(this.presetType())this.form.controls['type'].setValue(this.presetType());const today=new Date().toISOString().slice(0,10);for(const key of ['transaction_date','competence_date','transferred_at','month'])if(this.form.controls[key])this.form.controls[key].setValue(today);if(this.form.controls['status'])this.form.controls['status'].setValue(this.presetType()==='income'?'received':'paid');this.showForm.set(true);}
  save():void{if(this.form.invalid)return;this.saving.set(true);this.error.set('');this.api.post(this.endpoint(),this.form.getRawValue()).subscribe({next:()=>{this.saving.set(false);this.showForm.set(false);this.load();},error:e=>{this.saving.set(false);this.error.set(e.error?.message??'Verifique os campos informados.');}});}
  remove(item:ApiItem):void{if(!confirm('Deseja realmente remover este registro?'))return;this.api.delete(`${this.endpoint()}/${item.id}`).subscribe(()=>this.load());}
  closeBackdrop(event:MouseEvent):void{if(event.target===event.currentTarget)this.showForm.set(false);}
  primary(item:ApiItem):string{return String(item['name']??item['description']??`Registro #${item.id}`);}
  secondary(item:ApiItem):string{return [item['type'],item['status'],item['transaction_date']??item['transferred_at']??item['month']].filter(Boolean).join(' · ');}
  amount(item:ApiItem):string{const value=item['amount']??item['current_balance']??item['planned_amount']??item['target_amount']??item['credit_limit'];return value===undefined?'':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}
}
