export interface FieldOption { label:string;value:string }
export interface FieldDefinition { key:string;label:string;type?:'text'|'number'|'date'|'select'|'textarea';required?:boolean;options?:FieldOption[];placeholder?:string }
const accountTypes=[{label:'Conta corrente',value:'checking'},{label:'Poupança',value:'savings'},{label:'Dinheiro',value:'cash'},{label:'Conta digital',value:'digital'},{label:'Investimento',value:'investment'},{label:'Outra',value:'other'}];
const transactionStatus=[{label:'Previsto',value:'planned'},{label:'Pendente',value:'pending'},{label:'Pago',value:'paid'},{label:'Recebido',value:'received'},{label:'Vencido',value:'overdue'},{label:'Cancelado',value:'cancelled'}];
export const schemas:Record<string,FieldDefinition[]>={
  accounts:[{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',type:'select',options:accountTypes,required:true},{key:'institution',label:'Instituição'},{key:'initial_balance',label:'Saldo inicial',type:'number',required:true},{key:'notes',label:'Observações',type:'textarea'}],
  transactions:[{key:'description',label:'Descrição',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'account_id',label:'ID da conta',type:'number',required:true},{key:'category_id',label:'ID da categoria',type:'number'},{key:'type',label:'Tipo',type:'select',options:[{label:'Receita',value:'income'},{label:'Despesa',value:'expense'}],required:true},{key:'transaction_date',label:'Data',type:'date',required:true},{key:'competence_date',label:'Competência',type:'date',required:true},{key:'due_date',label:'Vencimento',type:'date'},{key:'status',label:'Status',type:'select',options:transactionStatus,required:true},{key:'notes',label:'Observações',type:'textarea'}],
  transfers:[{key:'from_account_id',label:'ID da conta de origem',type:'number',required:true},{key:'to_account_id',label:'ID da conta de destino',type:'number',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'transferred_at',label:'Data',type:'date',required:true},{key:'description',label:'Descrição'}],
  cards:[{key:'name',label:'Nome do cartão',required:true},{key:'institution',label:'Instituição'},{key:'payment_account_id',label:'ID da conta de pagamento',type:'number',required:true},{key:'credit_limit',label:'Limite',type:'number',required:true},{key:'closing_day',label:'Dia do fechamento',type:'number',required:true},{key:'due_day',label:'Dia do vencimento',type:'number',required:true}],
  budgets:[{key:'category_id',label:'ID da categoria',type:'number',required:true},{key:'month',label:'Primeiro dia do mês',type:'date',required:true},{key:'planned_amount',label:'Valor planejado',type:'number',required:true}],
  goals:[{key:'name',label:'Nome',required:true},{key:'description',label:'Descrição',type:'textarea'},{key:'target_amount',label:'Valor alvo',type:'number',required:true},{key:'current_amount',label:'Valor atual',type:'number'},{key:'target_date',label:'Data alvo',type:'date'},{key:'status',label:'Status',type:'select',options:[{label:'Ativa',value:'active'},{label:'Pausada',value:'paused'},{label:'Concluída',value:'completed'}],required:true}],
};
