import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild, inject, signal } from '@angular/core';
import { Chart, ChartConfiguration, registerables } from 'chart.js';
import { ApiService } from '../../core/api.service';
Chart.register(...registerables);
interface Summary { current_balance:string;projected_balance:string;monthly_income:string;monthly_expense:string;monthly_result:string;savings_rate:number;payable:string;receivable:string }
interface DashboardData { summary:Summary;monthly:{month:string;type:string;total:string}[];categories:{name:string;total:string}[];recent:{id:number;description:string;amount:string;type:string;transaction_date:string;status:string}[];goals:{id:number;name:string;current_amount:string;target_amount:string}[];upcoming:{id:number;description:string;amount:string;due_date:string}[] }
@Component({selector:'app-dashboard',template:`
<section><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Resumo financeiro</p><h1 class="mt-1 text-3xl font-black">Visão geral</h1><p class="mt-2 text-slate-500">Acompanhe o que importa neste mês.</p></section>
@if (loading()) { <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@for(i of [1,2,3,4,5,6,7,8];track i){<div class="h-32 animate-pulse rounded-2xl bg-slate-200"></div>}</div> }
@if (data(); as dashboard) {
<div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@for(card of cards(dashboard.summary);track card.label){<article class="card p-5"><p class="text-sm font-semibold text-slate-500">{{card.label}}</p><p class="mt-2 text-2xl font-black" [class.text-emerald-700]="card.good">{{card.value}}</p><p class="mt-1 text-xs text-slate-400">{{card.hint}}</p></article>}</div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><article class="card p-6 xl:col-span-2"><h2 class="font-black">Receitas x despesas</h2><div class="mt-4 h-72"><canvas #monthlyChart aria-label="Gráfico de receitas e despesas"></canvas></div></article><article class="card p-6"><h2 class="font-black">Gastos por categoria</h2><div class="mt-4 h-72"><canvas #categoryChart aria-label="Gráfico de categorias"></canvas></div></article></div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><article class="card overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Últimas movimentações</h2></div>@for(item of dashboard.recent;track item.id){<div class="flex items-center justify-between border-b border-slate-100 px-5 py-4 last:border-0"><div><p class="font-semibold">{{item.description}}</p><p class="text-xs text-slate-400">{{item.transaction_date}} · {{item.status}}</p></div><p class="font-black" [class.text-emerald-700]="item.type==='income'" [class.text-red-600]="item.type==='expense'">{{item.type==='expense'?'-':'+'}}{{money(item.amount)}}</p></div>}@empty{<p class="p-8 text-center text-slate-500">Nenhuma movimentação ainda.</p>}</article><article class="card p-5"><h2 class="font-black">Metas financeiras</h2><div class="mt-5 space-y-5">@for(goal of dashboard.goals;track goal.id){<div><div class="flex justify-between text-sm"><span class="font-semibold">{{goal.name}}</span><span>{{percent(goal)}}%</span></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-emerald-500" [style.width.%]="percent(goal)"></div></div><p class="mt-1 text-xs text-slate-400">{{money(goal.current_amount)}} de {{money(goal.target_amount)}}</p></div>}@empty{<p class="py-8 text-center text-slate-500">Crie sua primeira meta.</p>}</div></article></div>
}
`,imports:[]})
export class Dashboard implements AfterViewInit,OnDestroy {
  private readonly api=inject(ApiService);
  @ViewChild('monthlyChart') monthlyCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('categoryChart') categoryCanvas?:ElementRef<HTMLCanvasElement>;
  readonly data=signal<DashboardData|null>(null);readonly loading=signal(true);private charts:Chart[]=[];private viewReady=false;
  constructor(){this.api.get<{data:DashboardData}>('dashboard').subscribe({next:r=>{this.data.set(r.data);this.loading.set(false);queueMicrotask(()=>this.renderCharts());},error:()=>this.loading.set(false)});}
  ngAfterViewInit():void{this.viewReady=true;this.renderCharts();}ngOnDestroy():void{this.charts.forEach(c=>c.destroy());}
  money(value:string|number):string{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}
  percent(goal:{current_amount:string;target_amount:string}):number{return Math.min(100,Math.round(Number(goal.current_amount)/Number(goal.target_amount)*100)||0);}
  cards(s:Summary){return [{label:'Saldo atual',value:this.money(s.current_balance),hint:'Contas ativas',good:true},{label:'Saldo projetado',value:this.money(s.projected_balance),hint:'Após pendências',good:Number(s.projected_balance)>=0},{label:'Receitas do mês',value:this.money(s.monthly_income),hint:'Competência atual',good:true},{label:'Despesas do mês',value:this.money(s.monthly_expense),hint:'Competência atual'},{label:'Resultado do mês',value:this.money(s.monthly_result),hint:'Receitas menos despesas',good:Number(s.monthly_result)>=0},{label:'Taxa de poupança',value:`${s.savings_rate}%`,hint:'Do total recebido',good:s.savings_rate>0},{label:'A pagar',value:this.money(s.payable),hint:'Pendente ou vencido'},{label:'A receber',value:this.money(s.receivable),hint:'Pendente ou vencido',good:true}];}
  private renderCharts():void{const d=this.data();if(!d||!this.viewReady||!this.monthlyCanvas||!this.categoryCanvas)return;this.charts.forEach(c=>c.destroy());this.charts=[];const months=[...new Set(d.monthly.map(i=>i.month))];const config:ChartConfiguration<'bar'>={type:'bar',data:{labels:months,datasets:[{label:'Receitas',data:months.map(m=>Number(d.monthly.find(i=>i.month===m&&i.type==='income')?.total??0)),backgroundColor:'#10b981',borderRadius:6},{label:'Despesas',data:months.map(m=>Number(d.monthly.find(i=>i.month===m&&i.type==='expense')?.total??0)),backgroundColor:'#f43f5e',borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}};this.charts.push(new Chart(this.monthlyCanvas.nativeElement,config));this.charts.push(new Chart(this.categoryCanvas.nativeElement,{type:'doughnut',data:{labels:d.categories.map(c=>c.name),datasets:[{data:d.categories.map(c=>Number(c.total)),backgroundColor:['#10b981','#0ea5e9','#8b5cf6','#f59e0b','#f43f5e','#64748b']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}}));}
}
