import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild, inject, signal } from '@angular/core';
import { Chart, ChartConfiguration, registerables } from 'chart.js';
import { ApiItem, ApiService } from '../../core/api.service';

Chart.register(...registerables);
interface Summary { current_balance:string;projected_balance:string;monthly_income:string;monthly_expense:string;monthly_result:string;savings_rate:number;payable:string;receivable:string;average_income:string;average_expense:string;overdue:string;fixed_expenses:string;variable_expenses:string }
interface DashboardData { summary:Summary;monthly:ApiItem[];net_worth_evolution:ApiItem[];categories:ApiItem[];account_spending:ApiItem[];card_spending:ApiItem[];accounts:ApiItem[];recent:ApiItem[];goals:ApiItem[];upcoming:ApiItem[];overdue:ApiItem[];budgets:ApiItem[];cards:ApiItem[];largest_expenses:ApiItem[] }

@Component({selector:'app-dashboard',template:`
<section><p class="text-sm font-bold uppercase tracking-widest text-emerald-700">Resumo financeiro</p><h1 class="mt-1 text-3xl font-black">Visão geral</h1><p class="mt-2 text-slate-500">Patrimônio, competência, caixa e compromissos em um único painel.</p></section>
@if(loading()){<div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@for(i of [1,2,3,4,5,6,7,8];track i){<div class="h-32 animate-pulse rounded-2xl bg-slate-200"></div>}</div>}
@if(data();as dashboard){
<div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@for(card of cards(dashboard.summary);track card.label){<article class="card p-5"><p class="text-sm font-semibold text-slate-500">{{card.label}}</p><p class="mt-2 text-2xl font-black" [class.text-emerald-700]="card.good" [class.text-red-600]="card.bad">{{card.value}}</p><p class="mt-1 text-xs text-slate-400">{{card.hint}}</p></article>}</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><article class="card p-6"><h2 class="font-black">Receitas x despesas</h2><div class="mt-4 h-72"><canvas #monthlyChart aria-label="Receitas e despesas por mês"></canvas></div></article><article class="card p-6"><h2 class="font-black">Evolução do saldo e patrimônio</h2><div class="mt-4 h-72"><canvas #balanceChart aria-label="Evolução do saldo e patrimônio"></canvas></div></article><article class="card p-6"><h2 class="font-black">Gastos por categoria</h2><div class="mt-4 h-72"><canvas #categoryChart aria-label="Gastos por categoria"></canvas></div></article><article class="card p-6"><h2 class="font-black">Gastos por conta e cartão</h2><div class="mt-4 h-72"><canvas #accountChart aria-label="Gastos por conta e cartão"></canvas></div></article><article class="card p-6"><h2 class="font-black">Orçamento por categoria</h2><div class="mt-4 h-72"><canvas #budgetChart aria-label="Orçamento planejado e realizado"></canvas></div></article><article class="card p-6"><h2 class="font-black">Despesas fixas x variáveis</h2><div class="mt-4 h-72"><canvas #expenseChart aria-label="Despesas fixas e variáveis"></canvas></div></article></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><article class="card overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Últimas movimentações</h2></div>@for(item of dashboard.recent;track item.id){<div class="flex justify-between border-b border-slate-100 px-5 py-3"><div><p class="font-semibold">{{item['description']}}</p><p class="text-xs text-slate-400">{{date(item['transaction_date'])}} · {{item['status']}}</p></div><b [class.text-red-600]="item['type']==='expense'" [class.text-emerald-700]="item['type']==='income'">{{money(item['amount'])}}</b></div>}@empty{<p class="p-8 text-center text-slate-500">Nenhuma movimentação.</p>}</article><article class="card p-5"><h2 class="font-black">Maiores despesas</h2><div class="mt-3 divide-y divide-slate-100">@for(item of dashboard.largest_expenses;track item['row_id']){<div class="flex justify-between py-3 text-sm"><span>{{item['description']}}</span><b>{{money(item['amount'])}}</b></div>}@empty{<p class="py-8 text-center text-slate-500">Sem despesas no mês.</p>}</div></article><article class="card p-5"><h2 class="font-black">Próximas contas</h2><div class="mt-3 divide-y divide-slate-100">@for(item of dashboard.upcoming;track item.id){<div class="flex justify-between py-3 text-sm"><span>{{item['description']}}<small class="block text-slate-400">{{date(item['due_date'])}}</small></span><b>{{money(item['amount'])}}</b></div>}@empty{<p class="py-8 text-center text-slate-500">Nada próximo do vencimento.</p>}</div></article></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><article class="card p-5"><h2 class="font-black">Orçamentos</h2><div class="mt-4 space-y-4">@for(item of dashboard.budgets;track item.id){<div><div class="flex justify-between text-sm"><span>{{nested(item,'category','name')}}</span><b [class.text-red-600]="item['indicator']==='exceeded'">{{item['percentage']}}%</b></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full" [class.bg-emerald-500]="item['indicator']==='normal'" [class.bg-amber-500]="item['indicator']==='near'" [class.bg-red-500]="item['indicator']==='exceeded'" [style.width.%]="barPercent(item['percentage'])"></div></div><p class="mt-1 text-xs text-slate-400">{{money(item['realized_amount'])}} de {{money(item['planned_amount'])}} · restante {{money(item['remaining_amount'])}}</p></div>}@empty{<p class="py-8 text-center text-slate-500">Nenhum orçamento neste mês.</p>}</div></article><article class="card p-5"><h2 class="font-black">Metas financeiras</h2><div class="mt-4 space-y-4">@for(goal of dashboard.goals;track goal.id){<div><div class="flex justify-between text-sm"><span>{{goal['name']}}</span><b>{{goalPercent(goal)}}%</b></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-emerald-500" [style.width.%]="goalPercent(goal)"></div></div></div>}@empty{<p class="py-8 text-center text-slate-500">Nenhuma meta ativa.</p>}</div></article><article class="card p-5"><h2 class="font-black">Próximas faturas</h2><div class="mt-3 divide-y divide-slate-100">@for(card of dashboard.cards;track card.id){@for(invoice of list(card,'invoices');track invoice.id){<div class="flex justify-between py-3 text-sm"><span>{{card['name']}}<small class="block text-slate-400">Vence {{date(invoice['due_date'])}}</small></span><b>{{money(invoice['total'])}}</b></div>}}@empty{<p class="py-8 text-center text-slate-500">Nenhuma fatura aberta.</p>}</div></article></div>
}
`,imports:[]})
export class Dashboard implements AfterViewInit,OnDestroy{
  private readonly api=inject(ApiService);@ViewChild('monthlyChart') monthlyCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('balanceChart') balanceCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('categoryChart') categoryCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('accountChart') accountCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('budgetChart') budgetCanvas?:ElementRef<HTMLCanvasElement>;@ViewChild('expenseChart') expenseCanvas?:ElementRef<HTMLCanvasElement>;
  readonly data=signal<DashboardData|null>(null);readonly loading=signal(true);private charts:Chart[]=[];private viewReady=false;
  constructor(){this.api.get<{data:DashboardData}>('dashboard').subscribe({next:r=>{this.data.set(r.data);this.loading.set(false);queueMicrotask(()=>this.renderCharts());},error:()=>this.loading.set(false)});}ngAfterViewInit():void{this.viewReady=true;this.renderCharts();}ngOnDestroy():void{this.charts.forEach(chart=>chart.destroy());}
  money(value:unknown):string{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));}date(value:unknown):string{return value?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(String(value))):'';}barPercent(value:unknown):number{return Math.min(100,Number(value)||0);}goalPercent(goal:ApiItem):number{return Math.min(100,Math.round(Number(goal['current_amount'])/Number(goal['target_amount'])*100)||0);}nested(item:ApiItem,key:string,property:string):string{return String((item[key] as ApiItem|undefined)?.[property]??'Sem categoria');}list(item:ApiItem,key:string):ApiItem[]{return Array.isArray(item[key])?item[key] as ApiItem[]:[];}
  cards(summary:Summary){return[{label:'Saldo atual',value:this.money(summary.current_balance),hint:'Caixa efetivado',good:Number(summary.current_balance)>=0,bad:Number(summary.current_balance)<0},{label:'Saldo projetado',value:this.money(summary.projected_balance),hint:'Após pendências e faturas',good:Number(summary.projected_balance)>=0,bad:Number(summary.projected_balance)<0},{label:'Receitas do mês',value:this.money(summary.monthly_income),hint:`Média ${this.money(summary.average_income)}`,good:true,bad:false},{label:'Despesas do mês',value:this.money(summary.monthly_expense),hint:`Média ${this.money(summary.average_expense)}`,good:false,bad:false},{label:'Resultado do mês',value:this.money(summary.monthly_result),hint:'Receitas menos despesas',good:Number(summary.monthly_result)>=0,bad:Number(summary.monthly_result)<0},{label:'Taxa de poupança',value:`${summary.savings_rate}%`,hint:'Do total recebido',good:summary.savings_rate>0,bad:summary.savings_rate<0},{label:'A pagar',value:this.money(summary.payable),hint:`Vencido ${this.money(summary.overdue)}`,good:false,bad:Number(summary.overdue)>0},{label:'A receber',value:this.money(summary.receivable),hint:'Previsto e pendente',good:true,bad:false}];}
  private renderCharts():void{const data=this.data();if(!data||!this.viewReady||!this.monthlyCanvas||!this.balanceCanvas||!this.categoryCanvas||!this.accountCanvas||!this.budgetCanvas||!this.expenseCanvas)return;this.charts.forEach(chart=>chart.destroy());this.charts=[];const months=[...new Set(data.monthly.map(item=>String(item['month'])))];const income=months.map(month=>Number(data.monthly.find(item=>item['month']===month&&item['type']==='income')?.['total']??0));const expense=months.map(month=>Number(data.monthly.find(item=>item['month']===month&&item['type']==='expense')?.['total']??0));const sources=[...data.account_spending.map(item=>({name:`Conta · ${item['name']}`,total:Number(item['total'])})),...data.card_spending.map(item=>({name:`Cartão · ${item['name']}`,total:Number(item['total'])}))];this.charts.push(new Chart(this.monthlyCanvas.nativeElement,this.bar(months,[{label:'Receitas',data:income,backgroundColor:'#10b981'},{label:'Despesas',data:expense,backgroundColor:'#f43f5e'}])));this.charts.push(new Chart(this.balanceCanvas.nativeElement,{type:'line',data:{labels:data.net_worth_evolution.map(item=>String(item['month'])),datasets:[{label:'Patrimônio líquido',data:data.net_worth_evolution.map(item=>Number(item['total'])),borderColor:'#0f766e',backgroundColor:'#ccfbf1',fill:true,tension:.3}]},options:this.options()}));this.charts.push(new Chart(this.categoryCanvas.nativeElement,this.doughnut(data.categories.map(item=>String(item['name'])),data.categories.map(item=>Number(item['total'])))));this.charts.push(new Chart(this.accountCanvas.nativeElement,this.doughnut(sources.map(item=>item.name),sources.map(item=>item.total))));this.charts.push(new Chart(this.budgetCanvas.nativeElement,this.bar(data.budgets.map(item=>this.nested(item,'category','name')),[{label:'Planejado',data:data.budgets.map(item=>Number(item['planned_amount'])),backgroundColor:'#94a3b8'},{label:'Realizado',data:data.budgets.map(item=>Number(item['realized_amount'])),backgroundColor:'#f59e0b'}])));this.charts.push(new Chart(this.expenseCanvas.nativeElement,this.doughnut(['Fixas','Variáveis'],[Number(data.summary.fixed_expenses),Number(data.summary.variable_expenses)])));}
  private bar(labels:string[],datasets:{label:string;data:number[];backgroundColor:string}[]):ChartConfiguration<'bar'>{return{type:'bar',data:{labels,datasets:datasets.map(item=>({...item,borderRadius:6}))},options:this.options()};}private doughnut(labels:string[],values:number[]):ChartConfiguration<'doughnut'>{return{type:'doughnut',data:{labels,datasets:[{data:values,backgroundColor:['#10b981','#0ea5e9','#8b5cf6','#f59e0b','#f43f5e','#64748b']}]},options:this.options()};}private options(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom' as const}}};}
}
